package app.example.com.mydemo.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import app.example.com.mydemo.greendao.SprayDetails;
import app.example.com.mydemo.greendao.DownloadDBEntity;

import app.example.com.mydemo.greendao.SprayDetailsDao;
import app.example.com.mydemo.greendao.DownloadDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sprayDetailsDaoConfig;
    private final DaoConfig downloadDaoConfig;

    private final SprayDetailsDao sprayDetailsDao;
    private final DownloadDao downloadDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sprayDetailsDaoConfig = daoConfigMap.get(SprayDetailsDao.class).clone();
        sprayDetailsDaoConfig.initIdentityScope(type);

        downloadDaoConfig = daoConfigMap.get(DownloadDao.class).clone();
        downloadDaoConfig.initIdentityScope(type);

        sprayDetailsDao = new SprayDetailsDao(sprayDetailsDaoConfig, this);
        downloadDao = new DownloadDao(downloadDaoConfig, this);

        registerDao(SprayDetails.class, sprayDetailsDao);
        registerDao(DownloadDBEntity.class, downloadDao);
    }
    
    public void clear() {
        sprayDetailsDaoConfig.getIdentityScope().clear();
        downloadDaoConfig.getIdentityScope().clear();
    }

    public SprayDetailsDao getSprayDetailsDao() {
        return sprayDetailsDao;
    }

    public DownloadDao getDownloadDao() {
        return downloadDao;
    }

}
